OrdererOrgs:
  - Name: MazenOrderer
    Domain: domain7.com
    Specs:
      - Hostname: HnaOrderer1

PeerOrgs:
  - Name: FBI
    Domain: FBI.domain7.com
    EnableNodeOUs: true
    Template:
      Count: 3
    Users:
      Count: 1

  - Name: NBA
    Domain: NBA.domain7.com
    EnableNodeOUs: true
    Template:
      Count: 3
    Users:
      Count: 1

