OrdererOrgs:
  - Name: MazenOrderer
    Domain: domain7.com
    Specs:
      - Hostname: HnaOrderer1

PeerOrgs:
  - Name: Yarab
    Domain: Yarab.domain7.com
    EnableNodeOUs: true
    Template:
      Count: 3
    Users:
      Count: 1

  - Name: YarabTany
    Domain: YarabTany.domain7.com
    EnableNodeOUs: true
    Template:
      Count: 3
    Users:
      Count: 1

